version: '3.9'

services:
  postgres:
    container_name: postgress
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=nestjs-course
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-course

volumes:
  postgres_data:

networks:
  nestjs-course:
